//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeUnit.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRealTimeUnitService")]
    public interface IRealTimeUnitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/AddRTU", ReplyAction="http://tempuri.org/IRealTimeUnitService/AddRTUResponse")]
        bool AddRTU(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/AddRTU", ReplyAction="http://tempuri.org/IRealTimeUnitService/AddRTUResponse")]
        System.Threading.Tasks.Task<bool> AddRTUAsync(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/SendValue", ReplyAction="http://tempuri.org/IRealTimeUnitService/SendValueResponse")]
        void SendValue(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnitService/SendValue", ReplyAction="http://tempuri.org/IRealTimeUnitService/SendValueResponse")]
        System.Threading.Tasks.Task SendValueAsync(string message, byte[] signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitServiceChannel : RealTimeUnit.ServiceReference.IRealTimeUnitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitServiceClient : System.ServiceModel.ClientBase<RealTimeUnit.ServiceReference.IRealTimeUnitService>, RealTimeUnit.ServiceReference.IRealTimeUnitService {
        
        public RealTimeUnitServiceClient() {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddRTU(string message, byte[] signature) {
            return base.Channel.AddRTU(message, signature);
        }
        
        public System.Threading.Tasks.Task<bool> AddRTUAsync(string message, byte[] signature) {
            return base.Channel.AddRTUAsync(message, signature);
        }
        
        public void SendValue(string message, byte[] signature) {
            base.Channel.SendValue(message, signature);
        }
        
        public System.Threading.Tasks.Task SendValueAsync(string message, byte[] signature) {
            return base.Channel.SendValueAsync(message, signature);
        }
    }
}
